---
name: flutter_r_demo
description: A demo to show how to use Flutter-R tool in flutter project
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "^0.1.2"
  r_dart_library:
    git:
      url: https://github.com/YK-Unit/r_dart_library.git
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - packages/flutter_r_demo/assets/images/$_test_begin_with_character$.png
  - packages/flutter_r_demo/assets/images/test_image_asset_variant_1.png
  - packages/flutter_r_demo/assets/images/test_image_asset_variant_2.png
  - packages/flutter_r_demo/assets/images/5_test_begin_with_number.png
  - packages/flutter_r_demo/assets/images/C_test_begin_with_capitalize.png
  - packages/flutter_r_demo/assets/images/_test_begin_with_character_.png
  - packages/flutter_r_demo/assets/images/test.png
  - packages/flutter_r_demo/assets/images/test.svg
  - packages/flutter_r_demo/assets/images/test_+-.·!@&$￥.svg
  - packages/flutter_r_demo/assets/images/test_sameName.gif
  - packages/flutter_r_demo/assets/images/test_sameName.jpg
  - packages/flutter_r_demo/assets/images/test_sameName.png
  - packages/flutter_r_demo/assets/jsons/test.json
  - packages/flutter_r_demo/assets/yamls/test.yaml
flr:
  version: 0.2.0
  assets:
  - lib/assets/images
  - lib/assets/jsons
  - lib/assets/yamls
